name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build bungee image
        uses: docker/build-push-action@v2
        with:
          context: ./bungee-core
          file: ./bungee-core/Dockerfile
          push: true
          tags: |
            docker.pkg.github.com/oms-opensource-minigame-server/oms-bungee/oms-bungeecore:${{ github.sha }}
            docker.pkg.github.com/oms-opensource-minigame-server/oms-bungee/oms-bungeecore:latest

      - name: Build spigot image
        uses: docker/build-push-action@v2
        with:
          context: ./spigot-core
          file: ./spigot-core/Dockerfile
          push: true
          tags: |
            docker.pkg.github.com/oms-opensource-minigame-server/oms-core/oms-spigotcore:${{ github.sha }}
            docker.pkg.github.com/oms-opensource-minigame-server/oms-core/oms-spigotcore:latest
